name: Build Pages

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build_pages:
    runs-on: ubuntu-latest
    name: Builds Github pages and updates gh-pages branch
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: npm run deploy
